
services:

  postgres:
    image: postgres:15
    container_name: experiment-postgres
    environment:
      POSTGRES_DB: experiments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./experiment-tracker
    container_name: experiment-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/experiments
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:
    build: ./experiment-ui
    container_name: experiment-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data:
