backend:
  replicas: 1
  image:
    repository: ghcr.io/marcvog/experiment-backend
    tag: v1.0.7

frontend:
  replicas: 1
  image:
    repository: ghcr.io/marcvog/experiment-frontend
    tag: v1.0.7
